apiVersion: apps/v1
kind: Deployment
metadata:
  name: modern-web-app
spec:
  template:
    spec:
      containers:
      - name: nginx
        env:
        - name: ENVIRONMENT
          value: "Development"