apiVersion: apps/v1
kind: Deployment
metadata:
  name: modern-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: modern-web-app
  template:
    metadata:
      labels:
        app: modern-web-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web-content
        configMap:
          name: web-content